spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081

# Fuerza a que el proceso de Java muera inmediatamente al detener la aplicación:
spring.devtools.restart.enabled=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.main.allow-bean-definition-overriding=true

